//
//  MemoryCalendarService.swift
//  MOMENTA
//
//  自动将通过 Memories 生成的歌曲写入系统日历，并附带回跳 deep link。
//

import Foundation
import EventKit

final class MemoryCalendarService {
    static let shared = MemoryCalendarService()

    private let eventStore = EKEventStore()
    private let defaults = UserDefaults.standard
    private let storageKey = "memory-calendar-events.v1"
    private var savedEventIdentifiers: [String: String]

    private init() {
        if let data = defaults.data(forKey: storageKey),
           let decoded = try? JSONDecoder().decode([String: String].self, from: data) {
            savedEventIdentifiers = decoded
        } else {
            savedEventIdentifiers = [:]
        }
    }

    func saveGeneratedSong(_ music: GeneratedMusic, context: MemoryMusicContext) async throws {
        guard music.status == .completed else { return }

        if let existingIdentifier = savedEventIdentifiers[music.id],
           eventStore.calendarItem(withIdentifier: existingIdentifier) != nil {
            return
        }

        try await ensureWriteAccess()

        guard let calendar = eventStore.defaultCalendarForNewEvents else {
            throw NSError(
                domain: "MemoryCalendarService",
                code: 2,
                userInfo: [NSLocalizedDescriptionKey: "No writable calendar is available."]
            )
        }

        let event = EKEvent(eventStore: eventStore)
        event.calendar = calendar
        event.title = music.title
        event.startDate = music.createdAt
        event.endDate = music.createdAt.addingTimeInterval(5 * 60)
        event.location = normalized(context.locationName)
        event.url = Self.deepLinkURL(for: music.id)
        event.notes = makeNotes(for: music, context: context)

        try eventStore.save(event, span: .thisEvent, commit: true)

        if let identifier = event.eventIdentifier {
            savedEventIdentifiers[music.id] = identifier
            persistSavedIdentifiers()
        }
    }

    static func deepLinkURL(for taskId: String) -> URL? {
        var components = URLComponents()
        components.scheme = "momenta"
        components.host = "memory-song"
        components.queryItems = [URLQueryItem(name: "taskId", value: taskId)]
        return components.url
    }

    private func ensureWriteAccess() async throws {
        switch EKEventStore.authorizationStatus(for: .event) {
        case .writeOnly, .fullAccess:
            return
        case .notDetermined:
            let granted = try await requestWriteOnlyAccess()
            guard granted else {
                throw NSError(
                    domain: "MemoryCalendarService",
                    code: 1,
                    userInfo: [NSLocalizedDescriptionKey: "Calendar access was denied."]
                )
            }
        case .denied, .restricted:
            throw NSError(
                domain: "MemoryCalendarService",
                code: 1,
                userInfo: [NSLocalizedDescriptionKey: "Calendar access is unavailable."]
            )
        @unknown default:
            throw NSError(
                domain: "MemoryCalendarService",
                code: 3,
                userInfo: [NSLocalizedDescriptionKey: "Unknown calendar authorization status."]
            )
        }
    }

    private func requestWriteOnlyAccess() async throws -> Bool {
        try await withCheckedThrowingContinuation { continuation in
            eventStore.requestWriteOnlyAccessToEvents { granted, error in
                if let error {
                    continuation.resume(throwing: error)
                } else {
                    continuation.resume(returning: granted)
                }
            }
        }
    }

    private func makeNotes(for music: GeneratedMusic, context: MemoryMusicContext) -> String {
        var lines: [String] = [
            "Generated by Memories"
        ]

        if let story = context.story, !story.isEmpty {
            lines.append("Memory: \(story)")
        }

        if !music.style.isEmpty {
            lines.append("Style: \(music.style)")
        }

        lines.append(context.instrumentalOnly ? "Mode: Instrumental" : "Mode: Vocal")

        if let weather = normalized(context.weather) {
            lines.append("Weather: \(weather)")
        }

        if let localTime = normalized(context.localTime) {
            lines.append("Captured: \(localTime)")
        }

        if let audioURL = music.audioURL?.absoluteString {
            lines.append("Audio: \(audioURL)")
        }

        return lines.joined(separator: "\n")
    }

    private func normalized(_ value: String?) -> String? {
        guard let trimmed = value?.trimmingCharacters(in: .whitespacesAndNewlines),
              !trimmed.isEmpty else {
            return nil
        }
        return trimmed
    }

    private func persistSavedIdentifiers() {
        guard let data = try? JSONEncoder().encode(savedEventIdentifiers) else { return }
        defaults.set(data, forKey: storageKey)
    }
}
